### ISSUE TITLE
npm install fails for node 0.8

### ISSUE THREAD

**Issue by fidian** [reid/node-jslint#107]
It appears that version 0.7.3 is using glob ^4.3.5, which node 0.8 does not understand.  I have a pull request that's failing its tests (see tests-always-included/pretty-js#13) because of this.  It looks like any future commit I add to the repository will also break.  Is it possible to use another, similar syntax?  eg ~4.3.5 or >4.3.5?

This may be related to issue #96, as though the same issue has cropped up with this newer version.

I don't see version 0.7.3 in this repository, yet it was pushed to npm.

**Comment by smikes** [comment]
Node 0.8 is supported but you need a newer npm. 

npm install -g npm@latest

**Comment by smikes** [comment]
Sorry about the repo inconsistency. 0.7.3 was pushed to my fork, not this repo. Now fixed.

**Comment by fidian** [comment]
I don't have a lot of control over Travis.  Is upgrading npm like this
normal?  I thought that npm shipped with node by default.

Should this issue be taken up with Travis CI instead?

**Comment by smikes** [comment]
You can update npm on Travis with a pre install command of the form above. 


I think there's one in jslint 'a Travis.yml actually. 




Normally I would try to make the stock 0.8 npm work but there's been an enormous amount of work on npm since then and it's a reasonably painless upgrade.

**Comment by smikes** [comment]
The nice thing about updating this way is that you no longer have to police your dependencies for ^ vs ~ syntax. (And their dependencies, recursively, until the end of the world).


It does represent pain for people actually running 0.8 in production but I haven't run into any of them yet.

**Comment by fidian** [comment]
Thanks for the tip about the before_install hook.  I copied the lines verbatim out of this project's .travis.yml file.  I really appreciate the swift feedback.

As for the dependencies for people actually using 0.8 in production, I don't think I'm too fussed about that.  jslint was only used for the devDependencies and typically people installing my module won't need to download and use jslint.
