### ISSUE TITLE
Add --no-filter option.

### ISSUE THREAD

**Issue by jordan-ayers** [reid/node-jslint#108]
It doesn't seem to be possible to run jslint on any file with 'node_modules' in the name anywhere.  What's worse, when called with a single absolute file name like that, it will do nothing and return a success code.  (Meaning that you can't get a confirmed check from a script for a given file; at least, not without capturing and analyzing the text output.  Maybe it passed, maybe it was considered 'not important'.)

Can a '--no-filter' option be added, so that it's at least possible to check these files without re-naming / linking or switching work directories?  I get that this isn't the normal use case; I'm not looking for any changes to defaults.

**Comment by smikes** [comment]
The intent was to allow `jslint **/*.js` without descending into the node_modules directory, so I'd call this a bug.  I will take a look at it later today.

**Comment by jordan-ayers** [comment]
Thanks.  I figured there was a shorthand like that for checking a full project, but hadn't used it myself.  I just was surprised that it had an effect on an explicit file list.

**Comment by smikes** [comment]
Implemented in latest , `jslint@0.8.0` published to npm.
