### ISSUE TITLE
Automatically recurse on directories

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#110]
As a former JSHint user, I would appreciate the ability to JSLint all of my code at once, with `jslint .`

But when I try this, I get an error:

```
$ npm run jslint

> regenboog@0.0.2 jslint /Users/andrew/Desktop/src/regenboog
> jslint .


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EISDIR, read
```

As a workaround, I can use https://github.com/davybrion/node-jslint-all

Could we merge jslint-all into official jslint, so that recursive directory scanning happens out of the box?

**Comment by smikes** [comment]
`node-jslint` supports the double-star glob, so you can probably get what you want with

```
jslint /Users/andrew/Desktop/src/regenboog/**/*.js
```

or even

```
jslint /Users/andrew/Desktop/src/regenboog/**/*
```

If all you have in that hierarchy are javascript files.

**Comment by smikes** [comment]
I'm not familiar with `node-jslint-all`.  It looks like it hasn't been updated in a while (it still uses edition `2011-04-21`), but if there's specific behavior from it that you'd like to see included, can you file an issue and point out the relevant functionality?

**Comment by mcandre** [comment]
Recursive globs are good, but in a large project, npm has trouble handling them.

```
$ npm run exec -- jslint **/*.js
bash: /Users/andrew/.nvm/v0.10.36/bin/npm: Argument list too long
```

To that end, could we add a check for directory names, and have jslint explicitly glob them when present?

**Comment by smikes** [comment]
How about this --
```
$ find . -name *.js | xargs npm run exec -- jslint
```

**Comment by mcandre** [comment]
Yes, I can write a unix `find` command as well. But I would like for jslint to behave like this automatically, without requiring me to do that.

**Comment by smikes** [comment]
Since you are using `grunt` you may wish to check out <https://github.com/stephenmathieson/grunt-jslint> which may provide traversal of the filesystem for you.

**Comment by smikes** [comment]
Closing, for reasons documented here: https://github.com/reid/node-jslint/issues/122#issuecomment-76546643

Thank you for making this feature request.
