### ISSUE TITLE
Provide configurable rule name in message output

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#111]
As a developer who agrees with some, but not all JSLint warnings, I want to easily know how to configure certain rules. When JSLint reports `Expected exactly one space between 'function' and '('.`, I have no idea how to turn this off, without searching through the entire JSLint codebase for the message.

Other linters like PyFlakes preface their messages with a standard name for the rule (e.g. `WH321` for a whitespace rule), to clearly communicate to the user how to refer to the rule in a configuration file.

**Comment by smikes** [comment]
You probably want `white: false` ; see the JSLint documentation here <http://www.jslint.com/lint.html> and the JSLint community here <https://plus.google.com/communities/104441363299760713736>

I should warn you that this is not the **main** JSLint project; for that, you should post on the JSLint community project.  This project just packages the code from <https://github.com/douglascrockford/JSLint> into an npm module that makes it convenient to use `jslint` with node and iojs.

**Comment by smikes** [comment]
JSLint error message text are not under node-jslint's control.

**Comment by mcandre** [comment]
Could we append this information to JSLint's error messages? It's really
hard to track down the config with just the default, generic messages.

On Thu, Mar 26, 2015 at 11:53 AM, Sam Mikes <notifications@github.com>
wrote:

> JSLint error message text are not under node-jslint's control.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reid/node-jslint/issues/111#issuecomment-86621481>.
>



-- 
Cheers,

Andrew Pennebaker
www.yellosoft.us
