### ISSUE TITLE
Exit status 1 when warnings are present

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#115]
As a command line `make` user, I want jslint to exit with code 1 (failure) when any lint warnings are detected, so that my build fails.

**Comment by smikes** [comment]
Thanks. This should have been the case a already, so this is a bug. I will have a look at the code around exit()

**Comment by smikes** [comment]
Can you please provide more context for this error, ideally a repro case?  I cannot reproduce the erroneous behavior here: for me, when there is an error, I get the expected exit code `1`.
