### ISSUE TITLE
Quiet option

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#116]
As a command line user, I want to be able to hide JSLint `<file> is OK.` messages, so that the output shows me more relevant information. A simple `-q` flag would make me happy :)

As a workaround, I can pipe jslint with `jslint <file> | grep -v ' is OK' | grep -v '^$'`, but I would prefer that jslint supported this feature natively.

**Comment by smikes** [comment]
I think --terse does this; does it not need your expectations?

**Comment by smikes** [comment]
*need -> Meet. (On a phone, sorry)

**Comment by mcandre** [comment]
Cheers!
