### ISSUE TITLE
Don't stop scanning on "Move 'var' declarations to the top of the function."

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#118]
If at all possible, please continue scanning the rest of my code, even when encountering `Move 'var' declarations to the top of the function.`

**Comment by smikes** [comment]
My apologies, but again, this is a Crockford-ism which would need to be addressed upstream and in my experience, is unlikely to change.

**Comment by mcandre** [comment]
I respect that JSLint is designed to emphasize this rule, but I don't want to hide other warnings just because this one is triggered.

A boolean option to explicitly enable/disable stopping scanning would be much appreciated.

**Comment by smikes** [comment]
This is not under our control.
