### ISSUE TITLE
Load --terse from .jslintrc

### ISSUE THREAD

**Issue by mcandre** [reid/node-jslint#120]
As a command line user, I want to be able to configure options like `--terse` in my `.jslintrc`, so that I don't have to manually type them every time I run jslint.

**Comment by smikes** [comment]
Thank you for pointing this out. This is also a bug; the config file should be able to set both node-jslint and jslint options.

**Comment by mcandre** [comment]
No problem!

What would the `.jslintrc` syntax be for this? `{ "--terse": true }`?

**Comment by smikes** [comment]
It should be { "terse": true }, parallel to the other options.

**Comment by mcandre** [comment]
Excellent, `{ "terse": true }` works for me!

You can close this issue, unless you'd like to expand the scope to include making this more clear in the documentation for node-jslint.
