### ISSUE TITLE
Uses of console global variable should raise an error

### ISSUE THREAD

**Issue by matiascelasco** [reid/node-jslint#123]
When *browser* and *devel* options are in their default values (which is false), uses of the *console* global variable should raise an error, just as happens in jslint.com

**Comment by smikes** [comment]
Thanks for the bug report.  Sorry, I was away for a while and didn't have a chance to respond to this.

I believe this happens because the default settings of node-jslint include `node:true`.  You can override this on the command line with `jslint --node=false` or `jslint --no-node`.

**Comment by matiascelasco** [comment]
Great! Thanks for the clarification.

**Comment by smikes** [comment]
Closing as answered.
