### ISSUE TITLE
assuming `node:true` even without declaration

### ISSUE THREAD

**Issue by zanona** [reid/node-jslint#125]
I am not sure if I am doing something wrong. But all my files are passing through OK when using `require`, `module`, `process`, etc, without the need of first declaring these variables.

I haven't set `node:true` or these variables globally anywhere else.

https://asciinema.org/a/17114

**Comment by smikes** [comment]
Node-jslint has "node: true" by default but you should be able to override it if needed.

**Comment by zanona** [comment]
thanks @smikes, I will declare that under `.jslintrc` then.
