### ISSUE TITLE
local config broken?

### ISSUE THREAD

**Issue by AdriVanHoudt** [reid/node-jslint#129]
I'm trying to update Lab to version 0.9 I got it mostly working except for local configs (you can see the build failing here https://travis-ci.org/AdriVanHoudt/lab/builds/64093893)
Is there something I'm missing?

**Comment by smikes** [comment]
Thanks, I will take a look at this today. Node-js lint recently got a dependency update (new jslint from doug crockford, upstream) and I may have to correct the interface between lab And jslint.

**Comment by AdriVanHoudt** [comment]
thanks for the quick response! And using v0.9 with older jslint seems to work so probably has to do with latests jslint

**Comment by Marsup** [comment]
@AdriVanHoudt looked at it, it's not broken, the rule "plusplus" doesn't exist anymore. Change the test for something with eval for example, I think this one will stick :)

**Comment by AdriVanHoudt** [comment]
Looks like @Marsup was right.
