### ISSUE TITLE
Add es6 option

### ISSUE THREAD

**Issue by emnh** [reid/node-jslint#131]
Looks like es6 is supported in jslint library, but somehow it's not possible to pass it as an option.

Adding this at the top of the file:

/*jslint browser: true, indent: 2, es6: true */

Gives:

index.js
 #1 Unexpected 'es6'.
    /*jslint browser: true, indent: 2, es6: true */ // Line 1, Pos 36

**Comment by smikes** [comment]
Are you using --edition=es6 on the command line?

**Comment by emnh** [comment]
Nope. Thanks! Works now.
