### ISSUE TITLE
Support local jslint editions

### ISSUE THREAD

**Issue by nomego** [reid/node-jslint#132]
Since we don't agree with 100% of Crockford's JSLint rules, we have to maintain our own fork (https://github.com/Neovici/JSLint/tree/all-patches) and therefore needs to add this edition to node-jslint every time jslint is updated.

Also anyone willing to contribute to projects needs to do the same to be able to follow our guidelines.

It would be a lot easier if we could just bundle our jslint edition with our projects and have node-jslint search for the jslint edition in the source code tree before trying to find the edition in the jslint lib folder.

**Comment by smikes** [comment]
I believe you can pass a path to "edition" and then you won't have to patch your distribution.

**Comment by smikes** [comment]
I have confirmed this with my local version of jslint --

```
$ jslint --edition=/path/to/jslint.js
```

does work and loads the custom edition specified by the path.  Can you try with your setup?

I am trying to clean up older issues, so if I don't hear back from you within a week, I will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!
