### ISSUE TITLE
Not supporting latest JSLint version (2015-05-08)

### ISSUE THREAD

**Issue by bryanjhv** [reid/node-jslint#133]
I was using the tool and noticed that everything works fine while the JSLint code exports a `JSLINT` function, but in latest version the function changed to `jslint` and when trying to use that edition, and reporting version, it shows `undefined`, also doing no lint at all (shows a lot of problems!).
**Capture when showing version**
![Capture when showing version](https://cloud.githubusercontent.com/assets/2767941/8708397/4b50bcd0-2b01-11e5-8cdc-e27263091317.png)
**Capture when linting**
![Capture when linting](https://cloud.githubusercontent.com/assets/2767941/8708457/b7f47caa-2b01-11e5-9f11-5a5ca533311c.png)
I suppose the error is in `nodelint.js`, when trying to detect which variable was exported by JSLint.

**Comment by bryanjhv** [comment]
Ok, I checked it and found linting in second image is fine (latest version is too much restrictive, and some options available in previous versions are missing), but the version is still showing as `undefined`.

**Comment by smikes** [comment]
Thanks for the bug report.  I will look into this over the weekend.

**Comment by bryanjhv** [comment]
I've also made a PR with some ideas on how to fix that :smile:

**Comment by smikes** [comment]
I believe this is fixed by the new jslint, 0.9.2  -- please try it out and let me know.

Thanks!

**Comment by bryanjhv** [comment]
Confirmed, it is working now. Thanks also :smiley:
