### ISSUE TITLE
Please support the new "fudge" option in JSLint

### ISSUE THREAD

**Issue by devdoc** [reid/node-jslint#135]
The new JSLint seems to default to 0-based indexing of row/column numbers, which creates problems when trying to map reported errors to text editors which usually use 1-based numbering (see devdoc/SublimeLinter-jslint#5). JSLint seems to include a new option called "fudge" that can be used to revert to 1-based numbers in its reports, but this option does not seem to work with node-jslint. This seems to happen even if the fudge option is included in the Javascript file to be linted as an inline option (`/*jslint fudge: true */`) which makes me wonder whether there is a bug in JSLint itself. The inline directive does seem to work on jslint.com, though.

**Comment by bryanjhv** [comment]
Yeah, that's a bit annoying because it works in JSLint web interface but when you open Developer tools and pass a JavaScript source to the `jslint` function, it is working the same as described... @douglascrockford, any explanation of this behavior?

**Comment by bryanjhv** [comment]
BTW, the file `report.js` in the JSLint repo seems to override `fudge` option only for reports. https://github.com/douglascrockford/JSLint/blob/430ff1f73384a7e002aefcf31c433a5737cd9ccd/report.js

**Comment by smikes** [comment]
Douglas doesn't come 'round here, this is the node-based repackaging of jslint.  I can take a look at this in the next day or so, thanks for bringing it up.

**Comment by pmw57** [comment]
After taking a quick look at things, the jslint.js script doesn't fudge the line/col values. Instead, it's the report.js file that provides the on-screen report and uses the data.option.fudge value to apply any needed fudging.

Line 37 of report.js:

    var fudge = +!!data.option.fudge;

**Comment by pmw57** [comment]
I have found good success by editing report.js - here's what needs to change.

Add a fudge variable to the `exports.report` function:

    errors,
    fudge = +!!lint.option.fudge,
    logger = this.logger,

Update the terse output

    logger.log(file + ':' + (e.line + fudge) + ':' + (col(e) + fudge) + ': ' + message(e));

Update the normal output

    line = ' // Line ' + (e.line + fudge) + ', Pos ' + (col(e) + fudge);

And that is all that needs to be done to report.js

The only other change is to update the SublimeLinter user settings, so that when you use the latest or es6 edition, you also include the fudge argument.

    "args": [
        "--edition=latest",
        "--fudge"
    ],

And job's done. The report will now update it's output based on a command-line config, a settings file, or a jslint directive at the top of the code.

**Comment by smikes** [comment]
Now supported - merged PR #150.  Thanks for the PR, sorry about the delay.
