### ISSUE TITLE
Node option enabled by default

### ISSUE THREAD

**Issue by tensor5** [reid/node-jslint#140]
This code

~~~ javascript
console.log("Hello!");
~~~

on [JSLint](http://www.jslint.com/) website outputs

~~~
Undeclared 'console'.
~~~

but `jslint --edition=es6` gives no warnings because the `node` option is enabled by default [here](https://github.com/reid/node-jslint/blob/master/lib/options.js#L42), as well as the obsolete `es5` option.
Could you add an option to run the plain JSLint function, with no extra options except those specified on the command line?

Thanks

**Comment by smikes** [comment]
I believe you can do this with '--no-node' on the command line:

```
$ cat foo.js
console.log("Hello!");

$ jslint --edition=es6 --no-node foo.js

foo.js
 #1 Undeclared 'console'.
    console.log("Hello!"); // Line 0, Pos 0
```
