### ISSUE TITLE
Release 0.9.4

### ISSUE THREAD

**Issue by voidus** [reid/node-jslint#142]
jslint-latest.js has been updated (specifically to include the ignore keyword) but no new version has been released. If you released 0.9.4, packagers could make it installable.

(I'm not very familiar with npm release processes, please excuse me if this doesn't make sense)

**Comment by smikes** [comment]
Thanks.  I must have forgotten to publish.

**Comment by smikes** [comment]
New version 0.9.5 with edition 2015-10-29 now published.

Thanks!
