### ISSUE TITLE
JSHint directive to ignore function expressions inside loops is not working

### ISSUE THREAD

**Issue by Virbhadrasinh** [reid/node-jslint#143]
I have following code where i am defining function in loop and added JSHint directive to ignore function expressions inside loops but its not working. Is there a way to ignore this?
<pre>
/*jshint loopfunc: true */
define(function(require) {
	"use strict";
	var _ = require('ivUnderscore');

	return {
		traverseBreadth: function (tree, iteratee) {
            var queue = [];
            queue.push(tree);

            while (queue.length > 0) {
                var node = queue.splice(0, 1)[0];
                /*jshint loopfunc: true */
                _.each(node.children, function (child) {
                    iteratee(child, node, this);
                    queue.push(child);
                }, this);
            }
        }
	};
});

</pre>
<pre>
 #1 Don't declare variables in a loop.
    var node = queue.splice(0, 1)[0]; // Line 12, Pos 21
 #2 Don't make functions within a loop.
    _.each(node.children, function (child) { // Line 14, Pos 39
</pre>

**Comment by smikes** [comment]
No.  JSLint does not honor many jshint directives.

In this case, the warning is intended to prevent you from unintentionally closing all functions over a loop index variable.

**Comment by Virbhadrasinh** [comment]
is there a list of supported jshint directives?
is there any plan to support rest of jshint directives?

**Comment by smikes** [comment]
Only the directives documented in jslint are supported. See http://www.jslint.com/help.html

Also please be aware that this is not the project that develops jslint: we just package it for use with node. You maybe want the Google group, https://plus.google.com/communities/104441363299760713736
