### ISSUE TITLE
How to download version 0.9.5 ?

### ISSUE THREAD

**Issue by saimn** [reid/node-jslint#144]
It seems that a version 0.9.5 was released, but there is no tag and I didn't find a way to download it (I'm maintaining the ArchLinux package). Could you make it available or simply tag it on the git repository ?
Thanks.

**Comment by smikes** [comment]
Sorry.  Tags were pushed to my private fork only before. I just fixed it: try now.

**Comment by saimn** [comment]
I don't see it on https://github.com/reid/node-jslint/tags ?

**Comment by smikes** [comment]
Interesting.  When I pushed it, I must have pushed my fork and not the `origin` repository.

Really fixed now; verified that 0.9.5 is present in Tags on reid/node-jslint

**Comment by saimn** [comment]
Thanks !
