### ISSUE TITLE
ES6 and classes

### ISSUE THREAD

**Issue by fidian** [reid/node-jslint#146]
I have been trying to lint the example from MDN:

```
class Polygon {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}
```

I have used the website jslint.com and checked the ES6 checkbox and it says information like the following:

```
Undeclared 'class'.
Expected ';' and instead saw 'Polygon'.
Undeclared 'Polygon'.
```

The list of errors goes on and on.  I've also tried the command line:  `jslint --edition=es6 test.js` and get similar results.  What am I doing wrong?  How can I lint my ES6 classes?

**Comment by ajhyndman** [comment]
JSLint takes a very conservative approach to ES6.  According to documentation, the ES6 option does the following:

> true if using the good parts of ECMAScript Sixth Edition. Some ES6 features are still under probation. Some ES6 features will never be good parts. It adds the same globals as this directive:

http://www.jslint.com/help.html

JSLint is the most opinionated linter on the market.  If you'd like to lint code that uses ES6 classes, you will need to use another linting tool, such as JSHint or ESHint.

**Comment by smikes** [comment]
^^ @ajhyndman is correct, JSLint doesn't consider classes to be a "good part".  Note also that this project is just the node support for running jslint; questions/requests for the jslint author should go to Douglas's Google+ group for jslint : https://plus.google.com/communities/104441363299760713736
