### ISSUE TITLE
Why does jslint assumes node, es5 as default options?

### ISSUE THREAD

**Issue by nikoskalogridis** [reid/node-jslint#151]
in [lib/options.js](https://github.com/reid/node-jslint/blob/master/lib/options.js#L42) you are merging as default options `node` and `es5`.

I use jslint for linting javascript files that are meant for the browser and I realised only recently that this hide a number of errors.

**Comment by smikes** [comment]
Those options were enabled by default by a previous maintainer.  Removing them from defaults would constitute a breaking change.  You should be able to override them in your own jslint config file, though.
