### ISSUE TITLE
How to configure whitespace in es6

### ISSUE THREAD

**Issue by mk-pmb** [reid/node-jslint#156]
Somehow it cannot accept two-spaces indentation in es6 mode, why is that and can it be fixed?

```diff
+$ nl -ba hello_world.js
      1  /*jslint indent: 2, maxlen: 80, node: true */
      2  console.log('hello' +
      3    ' world');
+$ jslint hello_world.js
 
 hello_world.js is OK.
+$ jslint --edition=es6 hello_world.js
 
 hello_world.js
- #1 Bad option 'indent'.
     /*jslint indent: 2, maxlen: 80, node: true */ // Line 0, Pos 0
- #2 Expected ' world' at column 8, not column 2.
     ' world'); // Line 2, Pos 2
+$ jslint --version
 node-jslint version: 0.10.1  JSLint edition 2013-08-26
```

**Comment by smikes** [comment]
It appears that the `indent` option is deprecated in jslint-es6, see http://www.jslint.com/help.html

Please note that this project, node-jslint, just provides the wrapper scripts.  jslint itself is written by Douglas Crockford ( https://github.com/douglascrockford/jslint ) with a discussion forum ( https://github.com/douglascrockford/jslint ) -- if you want an explanation for Douglas's decisions and/or to make feature requests about the actual linter, that's the place to do it.

If you'd like a more configurable and less strict linter, check out eslint: http://eslint.org

**Comment by mk-pmb** [comment]
Will do, thanks!

**Comment by mk-pmb** [comment]
I made a [feature request](https://github.com/douglascrockford/JSLint/issues/190) and an experimental implementation of custom indentation. If anyone more well-versed in jslint could have a look, I'd appreciate that.

**Comment by mk-pmb** [comment]
Update: Current jslint doesn't accept any indentation config, it's hard-coded to 4 spaces, with magic numbers even. The `--indent=` option to node-jslint doesn't have any effect anymore.
→ Should node-jslint thus warn if `--indent=` is given for a 2015-or-later edition?

Looks like DC doesn't like to, or couldn't yet spare the time to, point me to an explanation of his decision against custom indentation.

In the time until I come to understand it, would you prefer I  try and research ways to
→ make node-jslint emulate the now missing `--indent=` support?
Or should I rather switch to eslint instead? In that case, do you know of a project that maintains an eslint config that mimics jslint?
