### ISSUE TITLE
--maxerr CLI option does not seem to work.

### ISSUE THREAD

**Issue by jdsutton** [reid/node-jslint#160]
Jslint stops after 5 errors. Using the --maxerr option I can get it to stop after fewer errors, but not more.

(It also exits with 1 which seems odd since the program ran normally)

Seems like there is either a bug or the documentation needs to be a little clearer.

**Comment by jdsutton** [comment]
Upon further investigation the behavior seems to be to stop after min(5, 1 + maxerr) errors which is very intuitive and limiting.

**Comment by smikes** [comment]
Maxerr is no longer supported in the latest versions of upstream jslint for es6.  I will remove it from the next version of the command line tool.
