### ISSUE TITLE
jslint-latest is not the latest version of JSLint

### ISSUE THREAD

**Issue by Skateside** [reid/node-jslint#161]
The version of JSLint in `lib/jslint-latest.js` is 2015-10-29 but the latest version in the `lib` folder is 2016-07-03 and the latest version of [JSLint itself](https://github.com/douglascrockford/JSLint/blob/master/jslint.js) is 2017-02-07.

Can the version be updated, please?

**Comment by smikes** [comment]
For backward compatibility, the "latest" means "latest es5 version".  If you specify --version=es6, you will get the latest version, just updated.

**Comment by szepeviktor** [comment]
@smikes npm gave me `jslint@0.11.0`
Could you clearify its origin?

**Comment by kostadinnm** [comment]
VSCode jslint extension depends on this module. The code isn't updated here on github, but from what's in my npm modules folder I assume it's using [jslint.js 2017-07-01](https://github.com/douglascrockford/JSLint/blob/ba9e4318004ae32e8402192117de9b48e1d32306/jslint.js) for ES6 at the moment. I suggest some kind of binding to the original releases, but there should be volunteers that at least follow the discusion here: [JSLint The JavaScript Code Quality Tool](https://plus.google.com/communities/104441363299760713736). I.e., one notable thing that I read was that Douglas asked whether to include modules' support sometime around the end of September.
Cheers,
Kostadin

**Comment by szepeviktor** [comment]
Thank you.

**Comment by smikes** [comment]
New release 0.12.0 has jslint-2018-01-26 as its --edition=es6
