### ISSUE TITLE
Missing releases on GitHub

### ISSUE THREAD

**Issue by jayvdb** [reid/node-jslint#171]
0.11 and 0.12 on https://www.npmjs.com/package/jslint are missing at https://github.com/reid/node-jslint/releases

**Comment by okuryu** [comment]
I tagged [v0.11.0](https://github.com/reid/node-jslint/releases/tag/v0.11.0) and [v0.12.0](https://github.com/reid/node-jslint/releases/tag/v0.12.0) on this repo. Thanks!
