### ISSUE TITLE
/\${USER:ID}/g triggers Expected a number and instead saw 'U'

### ISSUE THREAD

**Issue by Mehuge** [reid/node-jslint#174]
The following RE

```javascript
/\${USER:ID}/g
```

Causes the following jslint errors

```
 #1 Expected a number and instead saw 'U'.
    /\${USER:ID}/g; // Line 1, Pos 4
 #2 Expected '}' and instead saw 'S'.
    /\${USER:ID}/g; // Line 1, Pos 5
 #3 Unescaped '}'.
    /\${USER:ID}/g; // Line 1, Pos 12
```
https://regexr.com/49oq7

**Comment by smikes** [comment]
Thanks!  You probably want to file that issue against Crockford's repository here: https://github.com/douglascrockford/JSLint

This repository, maintained by different people, just packages Crockford's linter as a command-line tool.
