### ISSUE TITLE
"--passfail false"

### ISSUE THREAD

**Issue by brettcave** [reid/node-jslint#39]
The "--passfail false" parameter does not seem to work as expected:

```
$ jslint --sloppy --white --vars --passfail false app.js

app.js
 #1 Move 'var' declarations to the top of the function.
    for (var i = 0; i < someVar; i++) { // Line 10, Pos 10
 #2 Stopping.  (25% scanned).
     // Line 10, Pos 10
```

--passfail true and --passfail false have been tried, both exit after the error.

**Comment by mcandre** [comment]
Same error for me. Looks like JSLint ignores this option, while JSHint follows it.

http://jslinterrors.com/stopping

**Comment by smikes** [comment]
@mcandre, I will create a separate issue (#124) so we do not keep sending email to @brettcave.

**Comment by jaseemabid** [comment]
Reproduced. --passfail [true|false] both stop parsing after 2 errors.

**Comment by smikes** [comment]
Please, no necromancy. Follow up on #124
