### ISSUE TITLE
"Use spaces, not tabs"

### ISSUE THREAD

**Issue by geoffreyvanwyk** [reid/node-jslint#65]
I get a "Use spaces, not tabs" error, when using node-jslint via a quick fix vim plugin. 

Is this part of JSLint? I do not see anything about spaces vs tabs on jslint.com.

**Comment by CottonEaster** [comment]
It is possible to disable this warning - right? _Right?_ If sanity prevails and the answer is 'yes', then, please: _how?_

**Comment by systemovich** [comment]
@CottonEaster try https://eslint.org/. It is completely configurable.
