### ISSUE TITLE
error installing with npm

### ISSUE THREAD

**Issue by eurekaa** [reid/node-jslint#96]
Hi,
i got an error with your package dependecies, npm doesn't find compatible versions.

I solved updating nodejs, maybe my npm version did'nt support a dependency definition like 'glob@^4.0.4' (maybe the ^ char?).

I report this just for information. My environment version before the update was:
node: 0.10.9
npm: 1.2.24

Thanks.

**Comment by smikes** [comment]
Actually, revisiting this, this is an `npm` dependency not a `node` dependency (since `npm@2.7.3` will run on node >= 0.8).  So I will not adjust the `engines` parameter, but I will update the documentation.
