### ISSUE TITLE
Man Page Not Saving Properly When Installing Modules Globally

### ISSUE THREAD

**Issue by pantocrator27** [reid/node-jslint#99]
Hey Guys:

I have the following set in my ~/.npmrc file:

prefix=/home/marshall/.local
manroot=/home/marshall/.local/man

When I perform npm install -g jslint, I would expect the jslint man page to be installed at /home/marshall/.local/man but it is not.

I tried to do some digging around but I could not find anything obviously incorrect.  I am wondering if this is an issue with the package or possibly node itself.

Thoughts?

~M

**Comment by smikes** [comment]
This is an `npm` bug, which may be fixed soon, as there is now a new pull request: https://github.com/npm/npm/issues/7299

**Comment by smikes** [comment]
This is fixed for me as of npm@2.7.3 (just happens to be the version I tested with).  @pantocrator27 , can you please see if it is now fixed for you with an updated `npm` ?

**Comment by pantocrator27** [comment]
I believe this did.  Thank you ever so much for following up on this!
